### PR TITLE
Fix for parity - This request is not supported because your node is running with state pruning. Run with --pruning=archive. - for GET rpc calls

### PR DESCRIPTION
**Pull request by vimukthi-git**
This issue is documented here https://github.com/MyCryptoHQ/MyCrypto/issues/2328
When we query for historic data we use `pending=true` to receive latest, but this creates a problem for parity because it activates this line https://github.com/paritytech/parity-ethereum/blob/7ba5652bea42f7a3bde9e8bdf917154c9ae11906/rpc/src/v1/impls/parity.rs#L452

Using `pending=false` solves the problem for parity and I was able to successfully anchor docs and even create NFTs
eg: https://kovan.etherscan.io/token/0x0417eb37941164368401d666984ced7694abcbb1?a=0x186158a678f4623ca1620bc933874dda6b8f7ed8

So I decided to remove the pending state when querying, @mikiquantum please comment whether this is an acceptable solution for geth as well. 

cc @Remi-Tuy (if you feel adventurous you can try out this branch, I think this bug was activated recently since https://github.com/MyCryptoHQ/MyCrypto/issues/2328 was reported after my previous round of testing - which was successful also)

Issue Link: <Github link>

### CODE REVIEW

**Comment by Remi-Tuy** [comment]
@vimukthi-git I will have a check today, will confirm if it works or not on here.

**Comment by Remi-Tuy** [comment]
Failed to `make install` this branch:

`grouped write of manifest, lock and vendor: failed to export github.com/centrifuge/centrifuge-protobufs: fatal: failed to unpack tree object f93686ceaf40283c7dc496c62fcc69b1c1a272e3
: exit status 128
Makefile:26: recipe for target 'install-deps' failed
make: *** [install-deps] Error 1`

**Comment by Remi-Tuy** [comment]
Failed to make install:

`ubuntu@ip-172-31-13-120:~/go/src/github.com/centrifuge/go-centrifuge$ make install
grouped write of manifest, lock and vendor: failed to export github.com/centrifuge/centrifuge-protobufs: fatal: failed to unpack tree object f93686ceaf40283c7dc496c62fcc69b1c1a272e3
: exit status 128
Makefile:26: recipe for target 'install-deps' failed
make: *** [install-deps] Error 1`

**Comment by vimukthi-git** [comment]
@Remi-Tuy
Note : You can just make install this branch and do 
centrifuge run for your previous config yaml. No need to create config.

**Comment by Remi-Tuy** [comment]
@vimukthi-git I assumed this, but the make install does not work, as stated above.

**Comment by vimukthi-git** [comment]
for the install error just do 
rm -rf vendor

And make install

**Comment by Remi-Tuy** [comment]
This could maybe be included in the MakeInstall file ? Would make this process easier :)

**Comment by vimukthi-git** [comment]
yes could be an improvement :)

**Comment by Remi-Tuy** [comment]
Doesn't seem to like this curl request:

`curl -k -X POST "https://localhost:8082/invoice" -H "
accept: application/json" -H "Content-Type: application/json" -d "{ \"data\": { \"invoice_stat
us\": \"new\", \"invoice_number\": \"test invoice 1\", \"sender_name\": \"Jane Doe\", \"curren
cy\": \"USD\", \"gross_amount\": \"100100\", \"due_date\": \"2019-01-01T08:18:22.167Z\", \"dat
e_created\": \"2018-10-19T08:18:22.167Z\" }}"`

Response:
`{"error":"'authorization' header missing"}`

**Comment by vimukthi-git** [comment]
@Remi-Tuy you are almost there
Add your centrifuge ID as the authorization header to your request. 
Eg: Authorization: <centrifuge id>

**Comment by vimukthi-git** [comment]
@mikiquantum I will merge this branch only after testing rinkeby and ropsten with all tests.

Thanks :)

**Comment by vimukthi-git** [comment]
@mikiquantum I will merge this as explained on DM there is no network specific bugs in this branch now. But the multi account bug needs to be fixed ASAP.

**Pull request merged**
